#!/bin/bash
DATE_SUFFIX=$(date +"%b%Y")
/snap/bin/chromium --headless --disable-gpu --no-pdf-header-footer --print-to-pdf="James_Eubanks_Resume_${DATE_SUFFIX}.pdf" ./JE-Resume.html
echo "Generated James_Eubanks_Resume_${DATE_SUFFIX}.pdf with no header and zero margins."
